### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [Descent098/ahd#10]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.4.0. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary ahd -w /tmp/ext ahd==0.4.0
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting ahd==0.4.0
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/735/200714f91de47/ahd-0.4.0.tar.gz (12 kB)
    ERROR: Command errored out with exit status 1:
     command: /tmp/venv/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-wheel-ixsgeh41/ahd/setup.py'"'"'; __file__='"'"'/tmp/pip-wheel-ixsgeh41/ahd/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-wheel-ixsgeh41/ahd/pip-egg-info
         cwd: /tmp/pip-wheel-ixsgeh41/ahd/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-wheel-ixsgeh41/ahd/setup.py", line 26, in <module>
        long_description = get_content("README.md", "CHANGELOG.md"),
      File "/tmp/pip-wheel-ixsgeh41/ahd/setup.py", line 16, in get_content
        with open(file, "r") as full_description:
    FileNotFoundError: [Errno 2] No such file or directory: 'CHANGELOG.md'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by Descent098** [comment]
PR merged into v0.5.0
